### PR TITLE
[THORN-2088] Update the Keycloak version to 3.4.3.Final

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by kenfinnigan** [comment]
Is this necessary for product alignment?

**Comment by sberyozkin** [comment]
@kenfinnigan May be not, not sure. I guess it has to be done at some point anyway, recall we agreed that we should follow at some point with this update after the keycloak-server fraction upgrade to 3.4.3.Final.
@Ladicek Thanks for the approval, at the moment it does not enable a Green merge button :-)

**Comment by sberyozkin** [comment]
Oh, I see it now :-)
Ken, I'll merge tomorrow morning if you won't object

**Comment by Ladicek** [comment]
My understanding is that this potentially doesn't change anything, but I think it's good to be on the latest version (in the respective stream) and have the core Thorntail project consistent with the Config API.

**Comment by mkouba** [comment]
+1 it's a bugfix version upgrade anyway..

**Review by mkouba — APPROVED** [review]

**Comment by sberyozkin** [comment]
Yes, the config api itself have not changed AFAIK, just good to keep it in sync, which is probably where I had some indirect association with the productization effort as well...

**Pull request merged**
