### PR TITLE
Update Keycloak from 2.5.4.Final to 3.2.1.Final

### PR DESCRIPTION
**Pull request by sventorben**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Review by kenfinnigan — APPROVED** [review]

**Comment by kenfinnigan** [comment]
retest this please

**Comment by sventorben** [comment]
What is the current status on this?

**Comment by kenfinnigan** [comment]
Apologies @sventorben, I've been swamped.

As this is a large bump in versions, we need to wait a little bit to stabilize some other pieces

**Comment by kenfinnigan** [comment]
Closing this is out of date as we're now in the process of updating to 3.4.0.Final

**Pull request closed without merging**
