### PR TITLE
Switched to wildfly config 1.1.0.Final

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
okay to test

**Comment by bobmcwhirter** [comment]
add to whitelist

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Retest this please again

**Comment by gastaldi** [comment]
Retest this please

**Review by bobmcwhirter — APPROVED** [review]

**Pull request merged**
