### PR TITLE
[THORN-2297] update to Keycloak 4.8.3.Final

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Marking _hold_ until we know which Keycloak version we'll update to. See THORN-2297 for more.

**Comment by Ladicek** [comment]
This is final and can be merged now.

**Comment by Ladicek** [comment]
test this please

**Comment by Ladicek** [comment]
test this pleases

**Review by juangon — APPROVED** [review]

**Pull request merged**
